# Generated by Django 2.1 on 2018-08-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('pop', models.IntegerField(default=0)),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('ALTISSIMA', 'Altissima')], default='BAIXA', max_length=10)),
                ('situacao_digital', models.IntegerField(choices=[(-2, 'emergencia!'), (-1, 'ruim'), (0, 'regular'), (1, 'bom'), (2, 'ótimo')], default=0)),
                ('situacao_territorio', models.IntegerField(choices=[(-2, 'emergencia!'), (-1, 'ruim'), (0, 'regular'), (1, 'bom'), (2, 'ótimo')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('tipo', models.CharField(choices=[('CODEPUTADO', 'CoDeputado'), ('DOBRADA', 'Dobrada'), ('MOBILIZADOR', 'Mobilizador')], default=None, max_length=10)),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('ALTISSIMA', 'Altissima')], default=0, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='cidade',
            name='colaboradores',
            field=models.ManyToManyField(to='dashboard.Colaborador'),
        ),
    ]
