# Generated by Django 2.1 on 2018-08-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='ra',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='cidade',
            name='votos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cidade',
            name='votos_marina',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='colaboradores',
            field=models.ManyToManyField(related_name='colaboradores_cidade', to='dashboard.Colaborador'),
        ),
    ]
