# Generated by Django 2.1 on 2018-08-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_colaborador_obs'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='tel',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
