# Generated by Django 2.1 on 2018-08-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_colaborador_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='rg',
            field=models.CharField(default='', max_length=200),
        ),
    ]
