# Generated by Django 2.1 on 2018-08-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_colaborador_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='tipo',
            field=models.CharField(choices=[('CODEPUTADO', 'CoDeputado'), ('DOBRADA', 'Dobrada'), ('AGENTE', 'Agente Público'), ('MOBILIZADOR', 'Mobilizador')], default=None, max_length=10),
        ),
    ]
