# Generated by Django 2.1 on 2018-08-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20180823_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='ibge',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
