# Generated by Django 2.1 on 2018-08-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_cidade_ibge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidade',
            name='ra',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='rg',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
