# Generated by Django 2.1 on 2018-08-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20180823_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='tipo',
            field=models.CharField(choices=[('CODEPUTADO', 'CoDeputado'), ('DOBRADA', 'Dobrada'), ('AGENTE', 'Agente Público'), ('MOBILIZA', 'Mobilizador')], default=None, max_length=10),
        ),
    ]
